# Generated by Django 4.2.2 on 2023-06-12 22:19

import car_collection.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_car_image_url_car_model_car_price_car_type_car_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[car_collection.web.validators.YearValidator(1980, 2049)]),
        ),
    ]
